### ISSUE TITLE
User Verification

### ISSUE THREAD

**Issue by Reece-McDonald** [Reece-McDonald/Software-Engineering#2]
Based on a user story, user verification is desired. We intend on making a way to have our system send an email to the input email, this email carrying a verification link to ensure the user is who they say they are. Additionally, we will be implementing a system to verify the user is a UF student, as only UF students can post and view the forum, while everyone else can only view it.

**Comment by Reece-McDonald** [comment]
After the backend and frontend were integrated, I recreated the parsing system so that it would work with the code we had in place for the frontend and backend integration.

**Comment by Reece-McDonald** [comment]
Ethan has started on the email system, but it's not quite in a fully functioning state for Sprint 2.

**Comment by wobbethan** [comment]
Email verification works, however emails we are using to send out verification keep getting hacked which forces google to shut them down. The functionality does work given on google sides they allow our email to send messages. Messages go to spam folder in UF email however
